### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by ScrolliStudio** [BigOtis/ainews#1]
Hello, first of all i appreciate your great effort to make this beautiful website available. I have zero coding experince, that's why when i see an error, i think the worst. Anyways, i pasted the mongo URL, chatgpt API key, however i got this error. Do you know what could be the reason? I made 4 hours research to fix that.

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at connectionStringHasValidScheme (/Users/nihat/ainews/node_modules/mongodb/node_modules/mongodb-connection-string-url/lib/index.js:9:30)
    at new ConnectionString (/Users/nihat/ainews/node_modules/mongodb/node_modules/mongodb-connection-string-url/lib/index.js:85:34)
    at parseOptions (/Users/nihat/ainews/node_modules/mongodb/lib/connection_string.js:191:17)
    at new MongoClient (/Users/nihat/ainews/node_modules/mongodb/lib/mongo_client.js:48:63)
    at Object.<anonymous> (/Users/nihat/ainews/server/controllers/articleController.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)

**Comment by BigOtis** [comment]
Hey, I can take a look later tomorrow to see if I can offer a clue. My
guess is that the Mongo DB connection string URL is incorrect or there's an
issue connecting since the error is occuring in the MONGO DB code

**Comment by ScrolliStudio** [comment]
Do you mean the .env file?

I created an .env file, inserted Chatgpt api key and mongo URL, my mongo url looks like this: 

mongodb+srv://username:password@server.sjhsce6.mongodb.net/?retryWrites=true&w=majority

![Screenshot 2023-12-14 at 16 36 11](https://github.com/BigOtis/ainews/assets/152308836/277f4140-ecfb-4dce-95cc-0716e9aa36e0)

**Comment by BigOtis** [comment]
Ever get it to work?

**Comment by ScrolliStudio** [comment]
I am able to connect MongoDB and run the server with npm start function. however, no web articles have shown up.

![Screenshot 2023-12-27 at 00 35 49](https://github.com/BigOtis/ainews/assets/152308836/3e0b86fe-b8ad-40d1-bcfc-a4f3c0fd396d)
![Screenshot 2023-12-27 at 00 35 54](https://github.com/BigOtis/ainews/assets/152308836/f79caa71-b203-46b1-924a-45711204a4f2)

**Comment by BigOtis** [comment]
Have you generated any with newsGen,js?

**Comment by BigOtis** [comment]
I see, I've forgotten to actually include that step in the readme.

If you run this standalone script, you can generate an article. You can also edit the newsGen.js call at the bottom of the code to run whatever search / news article generated you'd like.

node server/util/newsGen.js

**Comment by ScrolliStudio** [comment]
I tried to do, however i got an error: 

TypeError: Configuration is not a constructor
    at Object.<anonymous> (/Users/nihat/ainews/server/util/openaiUtils.js:22:23)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/nihat/ainews/server/util/newsGen.js:7:97)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    
btw, i managed to connect mongo URL

**Comment by BigOtis** [comment]
There were some issues with the news scraper that I fixed. You can try to pull the latest changes and see how things are working for you.

**Comment by ScrolliStudio** [comment]
Thank you so much, i'll keep you updated.

**Comment by ScrolliStudio** [comment]
I got this error during "npm run server"

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at connectionStringHasValidScheme (/Users/nihat/ainews/node_modules/mongodb-connection-string-url/lib/index.js:9:30)
    at new ConnectionString (/Users/nihat/ainews/node_modules/mongodb-connection-string-url/lib/index.js:85:34)
    at parseOptions (/Users/nihat/ainews/node_modules/mongodb/lib/connection_string.js:191:17)
    at new MongoClient (/Users/nihat/ainews/node_modules/mongodb/lib/mongo_client.js:48:63)
    at Object.<anonymous> (/Users/nihat/ainews/server/controllers/articleController.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)


I've installed my documents and integrate to MongoSB and chatGpt. 

![Screenshot 2024-01-08 at 01 31 38](https://github.com/BigOtis/ainews/assets/152308836/f93bb200-0fab-4ec9-b486-29e8e04506e6)

**Comment by ScrolliStudio** [comment]
Btw, after i run "npm install" i got some vulnerabilities:

`
up to date, audited 1986 packages in 7s

131 packages are looking for funding
  run `npm fund` for details

131 vulnerabilities (1 low, 104 moderate, 22 high, 4 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.`

**Comment by BigOtis** [comment]
> I got this error during "npm run server"
> 
> TypeError: Cannot read properties of undefined (reading 'startsWith') at connectionStringHasValidScheme (/Users/nihat/ainews/node_modules/mongodb-connection-string-url/lib/index.js:9:30) at new ConnectionString (/Users/nihat/ainews/node_modules/mongodb-connection-string-url/lib/index.js:85:34) at parseOptions (/Users/nihat/ainews/node_modules/mongodb/lib/connection_string.js:191:17) at new MongoClient (/Users/nihat/ainews/node_modules/mongodb/lib/mongo_client.js:48:63) at Object. (/Users/nihat/ainews/server/controllers/articleController.js:5:16) at Module._compile (node:internal/modules/cjs/loader:1376:14) at Module._extensions..js (node:internal/modules/cjs/loader:1435:10) at Module.load (node:internal/modules/cjs/loader:1207:32) at Module._load (node:internal/modules/cjs/loader:1023:12) at Module.require (node:internal/modules/cjs/loader:1235:19)
> 
> I've installed my documents and integrate to MongoSB and chatGpt.
> 
> ![Screenshot 2024-01-08 at 01 31 38](https://private-user-images.githubusercontent.com/152308836/294794499-f93bb200-0fab-4ec9-b486-29e8e04506e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NzcyMzYsIm5iZiI6MTcwNzg3NjkzNiwicGF0aCI6Ii8xNTIzMDg4MzYvMjk0Nzk0NDk5LWY5M2JiMjAwLTBmYWItNGVjOS1iNDg2LTI5ZThlMDQ1MDZlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQwMjE1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmZlOTAzZjE1MDJhODE5YTljZDA2ZjcxN2VkYmUwOTYyN2I0NzI2OWQxNGNkN2IyYTQ3MmNmMGM4Yjg4MWM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZGxmcGr1qJuxe7ekXprXmijCYXSaVpHL7jSam7Lj17c)

Hey, it just seems like the envar for your MongoDB connectionString isn't being set or pulled in correctly. You may want to try hard coding the string / double checking how you're setting the environment up.

If you're still trying to get it going, I'd be happy to hop on Discord and debug with you.

**Comment by ScrolliStudio** [comment]
If you could hit me up on @nht8969at discord, i'll be awesome, i tried many things and it didn't work. I can enrich this project with content, but i even couldn't make it run.

**Comment by BigOtis** [comment]
> If you could hit me up on @nht8969at discord, i'll be awesome, i tried many things and it didn't work. I can enrich this project with content, but i even couldn't make it run.

Cool - I added you a discord
